#!/bin/bash
# change the name of kaptan to.... 

main() {
  for file in `find . -type f`; do
    sed -i "s/kaptan/$(lower $@)/g" "$file"
    sed -i "s/Kaptan/$(camel $@)/g" "$file"
  done
}

lower() {
  echo $@ | tr A-Z a-z
}

upper() {
  echo $@ | tr a-z A-Z
}

camel() {
  #for word in $*; do
  #  echo -n "$(upper $(grep -o ^. <<< $word))$(lower $(sed 's/^.//' <<< $word)) "
  #done
  #echo
  echo "$(upper $(grep -o ^. <<< $@))$(lower $(sed 's/^.//' <<< $@))"
}

[[ -n $1 ]] && main $@
