#!/bin/bash

echo "==>        KAPUDAN        <=="
echo "Performing root actions..."

enable_notifier() {
    echo " Adding octopi-notifier to autostart apps..."
    install -Dm755 /usr/share/applications/octopi-notifier.desktop \
        /usr/share/autostart/octopi-notifier.desktop
    echo "  Done."
}

disable_notifier() {
    echo " Removing octopi-notifier from autostart apps..."
    rm /usr/share/autostart/octopi-notifier.desktop
    echo "  Done."
}


enable_daemon() {
    # internal function, $1 is daemon to enable
    systemctl enable $1
    systemctl start $1
}

disable_daemon() {
    # internal function, $1 is daemon to disable
    systemctl disable $1
    systemctl stop $1
}

enable_repo() {
    # internal function, $1 is repo to enable
    sed -i "/^#\[$1\]/,/^#/s/#//" /etc/pacman.conf
}

disable_repo() {
    # internal function, $1 is repo to disable
    sed -i "/^\[$1\]/,/^Include/s/^/#/" /etc/pacman.conf
}

enable_cups() {
    echo " Enabling the CUPS printing service..."
    enable_daemon org.cups.cupsd
    enable_daemon cups-browsed
    echo "  Done."
}

disable_cups() {
    echo " Disabling the CUPS printing service..."
    disable_daemon org.cups.cupsd
    disable_daemon cups-browsed
    echo "  Done."
}

enable_blue() {
    echo " Enabling the Bluetooth service..."
    enable_daemon bluetooth
    echo "  Done."
}

disable_blue() {
    echo " Disabling the Bluetooth service..."
    disable_daemon bluetooth
    echo "  Done."
}

enable_clam() {
    echo " Enabling the ClamAV service..."
    enable_daemon clamd
    enable_daemon freshclamd
    echo "  Done."
}

disable_clam() {
    echo " Disabling the ClamAV service..."
    disable_daemon clamd
    disable_daemon freshclamd
    echo "  Done."
}

enable_fire() {
    echo " Enabling the UFW firewall..."
    enable_daemon ufw
    ufw enable
    echo "  Done."
}

disable_fire() {
    echo " Disabling the UFW firewall..."
    disable_daemon ufw
    ufw disable
    echo "  Done."
}

enable_extra() {
    echo " Enabling the [extra] repo..."
    enable_repo extra
    pacman -Sy
    echo "  Done."
}

disable_extra() {
    echo " Disabling the [extra] repo..."
    disable_repo extra
    pacman -Sy
    echo "  Done."
}

if ! [[ $UID == 0 || $EUID == 0 ]]; then
    # not root
    echo "must be root"
    exit 1
fi

# argument parsing
echo "$@" | grep -q "enable_notifier"  && enable_notifier
echo "$@" | grep -q "disable_notifier" && disable_notifier
echo "$@" | grep -q "enable_cups"  && enable_cups
echo "$@" | grep -q "disable_cups" && disable_cups
echo "$@" | grep -q "enable_blue"  && enable_blue
echo "$@" | grep -q "disable_blue" && disable_blue
echo "$@" | grep -q "enable_clam"  && enable_clam
echo "$@" | grep -q "disable_clam" && disable_clam
echo "$@" | grep -q "enable_fire"  && enable_fire
echo "$@" | grep -q "disable_fire" && disable_fire
echo "$@" | grep -q "enable_extra"  && enable_extra
echo "$@" | grep -q "disable_extra" && disable_extra

# all done
echo "All done!"
echo "Press Enter to continue."
read me
exit
